### ISSUE TITLE
Better encoding

### ISSUE THREAD

**Issue by markoradak** [spion/subsync#2]
Having an option to set custom encoding would make this a whole lot better. Currently, any non UTF-8 character gets overwritten with `?`, and there are a lot of languages that contain non UTF-8 chars. I guess using something like `iconv` would be helpful there. And possibly having an option to change encoding via `subsync --set-encoding "Windows-1250"`, or similar.

Thoughts? :)

**Comment by cristianmiranda** [comment]
@markoradak @spion I created a PR addressing this issue: https://github.com/spion/subsync/pull/4
It doesn't make use of iconv nor similar since I wanted to keep it simple and change the script not that much.
Let me know if you have any questions.
